<!DOCTYPE html><html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta charset="utf-8"><meta http-equiv="X-UA-Compatible" content="chrome=1"><title>SublimePeek | Help for try...catch</title><link href="css/bootstrap.min.css" rel="stylesheet"><style type="text/css">  body {  padding-top: 10px;  padding-bottom: 20px;  padding-left: 10%;  padding-right: 10%;  }  .sidebar-nav {  padding: 9px 0;  }</style><link href="css/bootstrap-responsive.min.css" rel="stylesheet"><link href="css/custom.css" rel="stylesheet">  </head><body><div style="display: block; "><div id="4eea835f8cd2963cba000002" class="page-header"><h2>try...catch</h2><!--CONTENT--><div id = "section_1"><span id = "Summary"></span><h3 class = "editable">Summary</h3><p>Marks a block of statements to try, and specifies a response, should an exception be thrown.</p><table class = "standard-table"> <tbody> <tr> <td class = "header" colspan = "2">Statement</td> </tr> <tr> <td>Implemented in:</td> <td>JavaScript 1.4 <p>JavaScript 1.5, NES 6.0: Added multiple catch clauses (Netscape extension).</p> </td> </tr> <tr> <td>ECMA Version:</td> <td>ECMA-262, Edition 3</td> </tr> </tbody></table></div><div id = "section_2"><span id = "Syntax"></span><h3 class = "editable">Syntax</h3><pre class = "eval">try {   <em>try_statements</em>}[catch (<em>exception_var_1</em> if <em>condition_1</em>) {   <em>catch_statements_1</em>}]...[catch (<em>exception_var_2</em>) {   <em>catch_statements_2</em>}][finally {   <em>finally_statements</em>}]</pre></div><div id = "section_3"><span id = "Parameters"></span><h3 class = "editable">Parameters</h3><dl> <dt><code>try_statements</code></dt> <dd>The statements to be executed.</dd></dl><dl> <dt><code>catch_statements_1</code>, <code>catch_statements_2</code></dt> <dd>Statements that are executed if an exception is thrown in the <code>try</code> block.</dd></dl><dl> <dt><code>exception_var_1</code>, <code>exception_var_2</code></dt> <dd>An identifier to hold an exception object for the associated <code>catch</code> clause.</dd></dl><dl> <dt><code>condition_1</code></dt> <dd>A conditional expression.</dd></dl><dl> <dt><code>finally_statements</code></dt> <dd>Statements that are executed after the <code>try</code> statement completes. These statements execute regardless of whether or not an exception was thrown or caught.</dd></dl></div><div id = "section_4"><span id = "Description"></span><h3 class = "editable">Description</h3><p>The <code>try</code> statement consists of a <code>try</code> block, which contains one or more statements, and at least one <code>catch</code> clause or a <code>finally</code> clause, or both. That is, there are three forms of the <code>try</code> statement:</p><ol> <li><code>try...catch</code></li> <li><code>try...finally</code></li> <li><code>try...catch...finally</code></li></ol><p>A <code>catch</code> clause contain statements that specify what to do if an exception is thrown in the <code>try</code> block. That is, you want the <code>try</code> block to succeed, and if it does not succeed, you want control to pass to the <code>catch</code> block. If any statement within the <code>try</code> block (or in a function called from within the <code>try</code> block) throws an exception, control immediately shifts to the <code>catch</code> clause. If no exception is thrown in the <code>try</code> block, the <code>catch</code> clause is skipped.</p><p>The <code>finally</code> clause executes after the <code>try</code> block and <code>catch</code> clause(s) execute but before the statements following the <code>try</code> statement. It always executes, regardless of whether or not an exception was thrown or caught.</p><p>You can nest one or more <code>try</code> statements. If an inner <code>try</code> statement does not have a <code>catch</code> clause, the enclosing <code>try</code> statement's <code>catch</code> clause is entered.</p><p>You also use the <code>try</code> statement to handle Java exceptions. See the <a title = "en/JavaScript/Guide" rel = "internal" href = "https://developer.mozilla.org/en/JavaScript/Guide">Core JavaScript 1.5 Guide</a> for information on Java exceptions.</p><div id = "section_5"><span id = "Unconditional_catch_clause"></span><h4 class = "editable">Unconditional <code>catch</code> clause</h4><p>When a single, unconditional <code>catch</code> clause is used, the <code>catch</code> block is entered when any exception is thrown. For example, when the exception occurs in the following code, control transfers to the <code>catch</code> clause.</p>          <pre name = "code" class = "js">try {   throw &quot;myException&quot;; // generates an exception}catch (e) {   // statements to handle any exceptions   logMyErrors(e); // pass exception object to error handler}</pre>        </div><div id = "section_6"><span id = "Conditional_catch_clauses"></span><h4 class = "editable">Conditional <code>catch</code> clauses</h4><p>You can also use one or more conditional <code>catch</code> clauses to handle specific exceptions. In this case, the appropriate <code>catch</code> clause is entered when the specified exception is thrown. In the following example, code in the <code>try</code> block can potentially throw three exceptions: <code>TypeError</code>, <code>RangeError</code>, and <code>EvalError</code>. When an exception occurs, control transfers to the appropriate <code>catch</code> clause. If the exception is not one of the specified exceptions and an unconditional <code>catch</code> clause is found, control transfers to that <code>catch</code> clause.</p><p>If you use an unconditional <code>catch</code> clause with one or more conditional <code>catch</code> clauses, the unconditional <code>catch</code> clause must be specified last. Otherwise, the unconditional <code>catch</code> clause will intercept all types of exception before they can reach the conditional ones.</p>          <pre name = "code" class = "js">try {   myroutine(); // may throw three exceptions} catch (e if e instanceof TypeError) {   // statements to handle TypeError exceptions} catch (e if e instanceof RangeError) {   // statements to handle RangeError exceptions} catch (e if e instanceof EvalError) {   // statements to handle EvalError exceptions} catch (e) {   // statements to handle any unspecified exceptions   logMyErrors(e); // pass exception object to error handler}</pre>        <p>Note: This functionality is not part of the ECMAScript specification.</p></div><div id = "section_7"><span id = "The_exception_identifier"></span><h4 class = "editable">The exception identifier</h4><p>When an exception is thrown in the <code>try</code> block, <em><code>exception_var</code></em> (e.g. the <code>e</code> in <code>catch (e)</code>) holds the value specified by the <code>throw</code> statement. You can use this identifier to get information about the exception that was thrown.</p><p>This identifier is local to the <code>catch</code> clause. That is, it is created when the <code>catch</code> clause is entered, and after the <code>catch</code> clause finishes executing, the identifier is no longer available.</p></div><div id = "section_8"><span id = "The_finally_clause"></span><h4 class = "editable">The <code>finally</code> clause</h4><p>The <code>finally</code> clause contains statements to execute after the <code>try</code> block and <code>catch</code> clause(s) execute but before the statements following the <code>try</code> statement. The <code>finally</code> clause executes regardless of whether or not an exception is thrown. If an exception is thrown, the statements in the <code>finally</code> clause execute even if no <code>catch</code> clause handles the exception.</p><p>You can use the <code>finally</code> clause to make your script fail gracefully when an exception occurs; for example, you may need to release a resource that your script has tied up. The following example opens a file and then executes statements that use the file (server-side JavaScript allows you to access files). If an exception is thrown while the file is open, the <code>finally</code> clause closes the file before the script fails.</p>          <pre name = "code" class = "js">openMyFile()try {   // tie up a resource   writeMyFile(theData);}finally {   closeMyFile(); // always close the resource}</pre>        </div></div><div id = "section_5"><span id = "Unconditional_catch_clause"></span><h4 class = "editable">Unconditional <code>catch</code> clause</h4><p>When a single, unconditional <code>catch</code> clause is used, the <code>catch</code> block is entered when any exception is thrown. For example, when the exception occurs in the following code, control transfers to the <code>catch</code> clause.</p>          <pre name = "code" class = "js">try {   throw &quot;myException&quot;; // generates an exception}catch (e) {   // statements to handle any exceptions   logMyErrors(e); // pass exception object to error handler}</pre>        </div><div id = "section_6"><span id = "Conditional_catch_clauses"></span><h4 class = "editable">Conditional <code>catch</code> clauses</h4><p>You can also use one or more conditional <code>catch</code> clauses to handle specific exceptions. In this case, the appropriate <code>catch</code> clause is entered when the specified exception is thrown. In the following example, code in the <code>try</code> block can potentially throw three exceptions: <code>TypeError</code>, <code>RangeError</code>, and <code>EvalError</code>. When an exception occurs, control transfers to the appropriate <code>catch</code> clause. If the exception is not one of the specified exceptions and an unconditional <code>catch</code> clause is found, control transfers to that <code>catch</code> clause.</p><p>If you use an unconditional <code>catch</code> clause with one or more conditional <code>catch</code> clauses, the unconditional <code>catch</code> clause must be specified last. Otherwise, the unconditional <code>catch</code> clause will intercept all types of exception before they can reach the conditional ones.</p>          <pre name = "code" class = "js">try {   myroutine(); // may throw three exceptions} catch (e if e instanceof TypeError) {   // statements to handle TypeError exceptions} catch (e if e instanceof RangeError) {   // statements to handle RangeError exceptions} catch (e if e instanceof EvalError) {   // statements to handle EvalError exceptions} catch (e) {   // statements to handle any unspecified exceptions   logMyErrors(e); // pass exception object to error handler}</pre>        <p>Note: This functionality is not part of the ECMAScript specification.</p></div><div id = "section_7"><span id = "The_exception_identifier"></span><h4 class = "editable">The exception identifier</h4><p>When an exception is thrown in the <code>try</code> block, <em><code>exception_var</code></em> (e.g. the <code>e</code> in <code>catch (e)</code>) holds the value specified by the <code>throw</code> statement. You can use this identifier to get information about the exception that was thrown.</p><p>This identifier is local to the <code>catch</code> clause. That is, it is created when the <code>catch</code> clause is entered, and after the <code>catch</code> clause finishes executing, the identifier is no longer available.</p></div><div id = "section_8"><span id = "The_finally_clause"></span><h4 class = "editable">The <code>finally</code> clause</h4><p>The <code>finally</code> clause contains statements to execute after the <code>try</code> block and <code>catch</code> clause(s) execute but before the statements following the <code>try</code> statement. The <code>finally</code> clause executes regardless of whether or not an exception is thrown. If an exception is thrown, the statements in the <code>finally</code> clause execute even if no <code>catch</code> clause handles the exception.</p><p>You can use the <code>finally</code> clause to make your script fail gracefully when an exception occurs; for example, you may need to release a resource that your script has tied up. The following example opens a file and then executes statements that use the file (server-side JavaScript allows you to access files). If an exception is thrown while the file is open, the <code>finally</code> clause closes the file before the script fails.</p>          <pre name = "code" class = "js">openMyFile()try {   // tie up a resource   writeMyFile(theData);}finally {   closeMyFile(); // always close the resource}</pre>        </div><div id = "section_9"><span id = "Examples"></span><h3 class = "editable">Examples</h3><p>See the examples for <a title = "en/JavaScript/Reference/Statements/throw" rel = "internal" href = "https://developer.mozilla.org/en/JavaScript/Reference/Statements/throw">throw</a>.</p></div><div id = "section_10"><span id = "See_also"></span><h3 class = "editable">See also</h3><ul> <li><a title = "en/JavaScript/Reference/Statements/throw" rel = "internal" href = "https://developer.mozilla.org/en/JavaScript/Reference/Statements/throw">throw</a></li> <li><a title = "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Error" rel = "internal" href = "https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Error">Error</a></li></ul><p>&nbsp;</p><p></p></div><!--NOTE--><p class="source-link">This content was sourced by <a href="http://dochub.io/">DocHub</a> from MDN.</p></div></div></body></html>